name: todo28
description: A simple todo list Flutter app.
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.5
  google_fonts: ^5.0.0
  flutter_slidable: ^3.0.0

  shared_preferences: ^2.0.15

  flutter_local_notifications: ^15.1.0
  timezone: ^0.9.0

  
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

